u21562246_HW3/Models/FileModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace u21562246_HW3.Models
{
    public class FileModel
    {
        public string FileName { get; set; }
    }
}

u21562246_HW3/Models/ModelForFile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace u21562246_HW3.Models
{
    public class ModelForFile
    {
        public string NameOfSelectedFile { get; set; }
    }
}

u21562246_HW3/Controllers/AboutMeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace u21562246_HW3.Controllers
{
    public class AboutMeController : Controller
    {
        // GET: AboutMe
        public ActionResult Index()
        {
            return View();
        }
    }
}

u21562246_HW3/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using u21562246_HW3.Models;

namespace u21562246_HW3.Controllers
{
    public class FilesController : Controller
    {
        // GET: Files
        public ActionResult Index()
        {
            //code to Fetch all files in the Folder (Directory).
            string[] filePaths = Directory.GetFiles(Server.MapPath("~/Media/Documents/"));

            //Copy File names to Model collection.
            List<FileModel> files = new List<FileModel>();
            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = Path.GetFileName(filePath) });
            }

            return View(files);
        }

        //code to download files
        public FileResult Download(string FileName)
        {
            //Build the File Path.
            string path = Server.MapPath("~/Media/Documents/") + FileName;

            //Read the File data into Byte Array.
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //Send the File to Download.
            return File(bytes, "application/octet-stream", FileName);
        }

        public ActionResult Delete(string FileName)
        {
            // code to delete file 
            string fullPath = Request.MapPath("~/Media/Documents/" + FileName);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath); 
                ViewBag.Status = "File was found and deleted";
            }
            else
            {

                ViewBag.Status = "File was not found and hence cannot be deleted";
            }
            return RedirectToAction("Index");
        }
    }
}

u21562246_HW3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace u21562246_HW3.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string btnOptionSelection, HttpPostedFileBase file)
        {
            ViewBag.Status = btnOptionSelection + " has been uploaded successfully";
            //code to check whther user wants to upload image
            if (btnOptionSelection == "Image")
            {
                //code to upload picture
                string NameOfPicture = System.IO.Path.GetFileName(file.FileName);
                string PathOfPicture = System.IO.Path.Combine(Server.MapPath("~/Media/Images"), NameOfPicture);
                // file is uploaded
                file.SaveAs(PathOfPicture);
            }
            if (btnOptionSelection == "video")
            {
                //code to upload video
                string NameOfPicture = System.IO.Path.GetFileName(file.FileName);
                string PathOfPicture = System.IO.Path.Combine(Server.MapPath("~/Media/Videos"), NameOfPicture);
                // file is uploaded
                file.SaveAs(PathOfPicture);

            }
            if (btnOptionSelection == "Document")
            {
                //code to upload Document
                string NameOfPicture = System.IO.Path.GetFileName(file.FileName);
                string PathOfPicture = System.IO.Path.Combine(Server.MapPath("~/Media/Documents"), NameOfPicture);
                // file is uploaded
                file.SaveAs(PathOfPicture);
            }

            return View();
        }

    }
}

u21562246_HW3/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using u21562246_HW3.Models;

namespace u21562246_HW3.Controllers
{
    public class ImagesController : Controller
    {
        // GET: Images
        
        public ActionResult Index()
        {
            //code to Fetch all files in the Folder (Directory).
            string[] filePaths = System.IO.Directory.GetFiles(Server.MapPath("~/Media/Images/"));

            //Copy File names to Model collection.
            List<Models.FileModel> files = new List<FileModel>();
            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = System.IO.Path.GetFileName(filePath) });
            }

            return View(files);
        }

        //code to download files
        public FileResult Download(string FileName)
        {
            //Build the Images Path.
            string path = Server.MapPath("~/Media/Images/") + FileName;

            //Read the Images data into Byte Array.
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //Send the Images to Download.
            return File(bytes, "application/octet-stream", FileName);
        }

        public ActionResult Delete(string FileName)
        {
            // code to delete Images 
            string fullPath = Request.MapPath("~/Media/Images/" + FileName);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
                ViewBag.Status = "Image was found and deleted";
            }
            else
            {

                ViewBag.Status = "Image was not found and hence cannot be deleted";
            }
            return RedirectToAction("Index");
        }
    }
}

u21562246_HW3/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using u21562246_HW3.Models;

namespace u21562246_HW3.Controllers
{
    public class VideosController : Controller
    {
        // GET: Videos


        public ActionResult Index()
        {
            //code to Fetch all Videos in the Folder (Directory).
            string[] filePaths = System.IO.Directory.GetFiles(Server.MapPath("~/Media/Videos/"));

            //Copy Videos names to Model collection.
            List<FileModel> files = new List<FileModel>();
            foreach (string filePath in filePaths)
            {
                files.Add(new FileModel { FileName = System.IO.Path.GetFileName(filePath) });
            }

            return View(files);
        }

        //code to download files
        public FileResult Download(string FileName)
        {
            //Build the Videos Path.
            string path = Server.MapPath("~/Media/Videos/") + FileName;

            //Read the Videos data into Byte Array.
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            //Send the Videos to Download.
            return File(bytes, "application/octet-stream", FileName);
        }

        public ActionResult Delete(string FileName)
        {
            // code to delete Videos 
            string fullPath = Request.MapPath("~/Media/Videos/" + FileName);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
                ViewBag.Status = "Video was found and deleted";
            }
            else
            {

                ViewBag.Status = "Video was not found and hence cannot be deleted";
            }
            return RedirectToAction("Index");
        }
    }
}

u21562246_HW3/Views/AboutMe/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<h2>A little something about Sena</h2>
<div class="jumbotron">
    <p>
        Since you could'nt help but wonder "about me"(see what i did there) the following page is dedicted to the most handsome and talented man:
        ME...
    </p>
    <div class="row">
        <div class="col-md-8">
            <h2>Bio</h2>
            <p>
                Sena short for Senamiso is a young handsome man and as his name suggests/translates he is someone who brings people immense amount of joy.
                He was born in the united kingdom and due to unfortunte circumstances e relocated to south Africa as a minor infant.Senamiso has lived his whole life in South Africa 
                and has graduated from high school Scared Heart college to be exact and is now in the University of Pretoria studying BSc Information and Knowledge Systems.
                I know at this point you are wondering why this talented, funny, charming young man chose such a course right?
                Truth be told it is not somthing he is passionate about but considering the climate we are in, it was the bestchoice for him; as it gaurantee's him a job once he graduates 
                which will help him take care of his family.

                Some of Sena's hobbies include modelling, philanthropy, readin, acting, talking and overall interacting with people. Sena is a part time model and is very very
                passionate about making money especially while doing something he enjoys. It is Sena's dream to one day become an icon with multiple big movies, series and to have worked with all
                his favorite designers such as Laduma, Thebe Magugu Lukhanya Mdingi, Travis Scott and Kanye West amongst many others.
            </p>

        </div>
        
    <div class="col-md-4">
        <h2>Senamiso</h2>
        <img src="~/Content/IMG_0045.jpg" alt="A rare picture of Senamiso" style="height:350px" >
    </div>
    </div>

</div>

u21562246_HW3/Views/Files/Index.cshtml
@using u21562246_HW3.Models 
@model List<FileModel>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@ViewBag.Status
<div class="jumbotron">


    <table class="table table-hover table-dark">
        <thead style="background-color:darkgrey">
            <tr>
                <th scope="col" style="width:60%">File Name </th>
                <th scope="col">Download Option</th>
                <th scope="col">Delete Option</th>
            </tr>
        </thead>
        <tbody>
                @foreach (var fileInModel in Model)
                {
                    <tr>
                        <td>@fileInModel.FileName</td>
                        <td><button type="button" class="btn btn-success">@Html.ActionLink("Download", "Download", new { FileName = fileInModel.FileName })</button></td>
                        <td><button type="button" class="btn btn-danger">@Html.ActionLink("Delete", "Delete", new { FileName = fileInModel.FileName })</button></td>
                    </tr>
                }

        </tbody>
    </table>
</div>

u21562246_HW3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

u21562246_HW3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2>Media</h2>
<div class="jumbotron">
    <p>Welcome to Media this page allows you as the user to upload images, videos and documents as well as download them.</p>
    <div class="row">
        <div class="col-md-8">
            <h2>Description of how the system works</h2>
            <p>
                This system is very easy to use all it requires id for the user to start off by selecting from the options 
                provided which are bettween documents, images and videos. Once the user has choosen the option by clicking 
                a radio button. The user may then press the "Choose file" button and upload a document if they have pressed the 
                document button, or image if they have choosen an image or a video if they have choosen a video.
                Once the user is done he/she may press the submit button and based on what he/she has uploaded they may use the NavBar
                to navigate towhat they want to see this may be a File, Image, Video or if the user is interested a short Bio about...
                Yess you guessed it Me!!!!
            </p>

        </div>
        @ViewBag.Status
        <div class="col-md-4">
            <h2>Options Selection</h2>
            @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <form>
                    <label>Document</label>
                    <input type="radio" name="btnOptionSelection" value="Document" />
                    <br />

                    <label>Images</label>
                    <input type="radio" name="btnOptionSelection" value="Image" />
                    <br />

                    <label>Videos</label>
                    <input type="radio" name="btnOptionSelection" value="Video"/>
                    <br />

                    <input type="file" name="file"  id="file"/>
                    <br />

                    <button type="submit">Submit</button>
                </form>
            }

        </div>
    </div>

</div>

u21562246_HW3/Views/Images/Index.cshtml
@using u21562246_HW3.Models
@model  List<FileModel>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@foreach(var ImageInModel in Model)
 {
    <div class="row">
        <div class="col-lg-4">
            <img src="~/Media/Images/@ImageInModel.FileName" style="height:350px" />
            <p>@ImageInModel.FileName</p>
            <button type="button" class="btn btn-success">@Html.ActionLink("Download", "Download", new { FileName = ImageInModel.FileName })</button>
            <button type="button" class="btn btn-danger">@Html.ActionLink("Delete", "Delete", new { FileName = ImageInModel.FileName })</button>
        </div>
    </div>
 }

u21562246_HW3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Files", "Index", "Files")</li>
                    <li>@Html.ActionLink("Images", "Index", "Images")</li>
                    <li>@Html.ActionLink("Videos", "Index", "Videos")</li>
                    <li>@Html.ActionLink("About Me", "Index", "AboutMe")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

u21562246_HW3/Views/Videos/Index.cshtml
@using u21562246_HW3.Models
@model  List<FileModel>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@foreach (var VideoInModel in Model)
{
    <div class="row">
        <div class="col-lg-4">
            <video height="300"controls="controls" autoplay>
                <source src="~/Media/Videos/@VideoInModel.FileName" type="video/mp4">
            </video>
            <p>@VideoInModel.FileName</p>
            <button type="button" class="btn btn-success">@Html.ActionLink("Download", "Download", new { FileName = VideoInModel.FileName })</button>
            <button type="button" class="btn btn-danger">@Html.ActionLink("Delete", "Delete", new { FileName = VideoInModel.FileName })</button>
        </div>
    </div>
}